version: '3.8'

services:
  neo4j:
    container_name: neo4j-database
    image: 'neo4j:latest'
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
    ports:
      - '7687:7687'
      - '7474:7474'

  mongodb:
    container_name: mongo-database
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}

  backend_service:
    build: ./social-network-visualizer-backend
    container_name: backend_container_inz
    ports:
      - '8080:8080'
    volumes:
      - ./social-network-visualizer-backend:/app
    depends_on:
      - mongodb
      - neo4j
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || wget --spider -q http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 200
    restart: on-failure

  frontend_service:
    build: ./social-network-visualizer-frontend
    container_name: frontend_container_inz
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - /app/.next
    stdin_open: true
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      backend_service:
        condition: service_healthy

volumes:
  mongo_data: